id: PADDDFF90
initial_creation_type: ocr
source_metadata:
  volumes:
    3addc17b1fca4255aba76a53160517fc:
      base_file: v088.txt
      image_group_id: I1PD95933
      title: ལས་བརྒྱ་རྩ་གཅིག་པ།
      total_pages: 1560
      volume_number: 88
